name: CI/CD Pipeline

# Define triggers: Push to develop/main, Pull Request, and manual run
on:
  push:
    branches:
      - develop
      - main
  pull_request:
  workflow_dispatch:  # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Lint code
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Build TypeScript app
        run: npm run build

      - name: Build Docker image
        run: docker build -t your-dockerhub-username/healthcare-app:latest .

      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

      - name: Push Docker image to Docker Hub
        run: docker push your-dockerhub-username/healthcare-app:latest
